#.Prepare the Data.
Create database Healthcare;
select * from appointment_sheet;
select * from billing_sheet;
select * from doctors_sheet;
select * from patient_sheet;
select * from treatment_sheet;
alter table appointment_sheet
change column `ï»¿appointment_id` appointment_id varchar(50);
alter table billing_sheet
change column `ï»¿bill_id` bill_id varchar(50);
alter table doctors_sheet
change column `ï»¿doctor_id` doctor_id varchar(50);
alter table patient_sheet
change column `ï»¿patient_id` patient_id varchar(50);
alter table treatment_sheet
change column `ï»¿treatment_id` treatment_id varchar(50);


#1.How many patients are registered in the hospital?
select count(patient_id) as Reg_Patients
from patient_sheet;


#2.How many doctors are working in the hospital?
select count(doctor_id) as 'Total_Working_Doctor'
from doctors_sheet;


#3.What is the total number of appointments?
select count(appointment_id) as Num_of_appointment
from appointment_sheet;


#4.How many appointments were completed, cancelled, or no-show?
select status,count(appointment_id) as Total_Appointment
from appointment_sheet
group by status
order by Total_Appointment desc;


#5.What is the gender distribution of patients?
select gender,count(patient_id) as Total_Patient
from patient_sheet
group by gender
order by Total_Patient desc;


#6.What is the average patient age?
select round(avg(age),0)as Avg_Age
from patient_sheet;


#7.Which payment methods are most commonly used?
select payment_method,count(bill_id) as total_Count
from billing_sheet
group by payment_method
order by total_Count desc;


#8.What is the total revenue generated (Paid bills only)?
 select payment_status,sum(amount)
 from billing_sheet
 where payment_status='paid';
 
 
 #9.How many bills are pending vs completed vs failed?
select payment_status,count(bill_id) total_count
from billing_sheet
group by payment_status
order by total_count desc;


#10.What is the average cost of treatments?
select treatment_type,avg(cost) as Total_Cost
from treatment_sheet
group by treatment_type
order by Total_cost desc;


#11.Which doctor handled the most appointments?
select `full Name`,count(patient_id) as Total_Appointments_Handled
from doctors_sheet
left join appointment_sheet
on doctors_sheet.doctor_id=appointment_sheet.doctor_id
group by `full Name`
order by Total_Appointments_Handled desc
limit 1;


#12.How many patients visited each doctor?
select `full Name`,count(patient_id) as Total_Appointments_Handled
from doctors_sheet
left join appointment_sheet
on doctors_sheet.doctor_id=appointment_sheet.doctor_id
group by `full Name`
order by Total_Appointments_Handled desc;


#13.What is the monthly trend of appointments?
SELECT 
MONTH(STR_TO_DATE(appointment_date, '%Y-%m-%d')) AS month,
COUNT(*) AS total_appointments
FROM appointment_sheet
WHERE appointment_date IS NOT NULL
GROUP BY month
ORDER BY month;


#14.What is the average treatment cost by treatment type?
select treatment_type,round(avg(cost),2) as avg_cost
from treatment_sheet
group by treatment_type
order by avg_cost desc;


#15.Which hospital branch has the most doctors?
select hospital_branch,count(doctor_id) as total_doctor
from doctors_sheet
group by hospital_branch
order by Total_Doctor desc;




#16.How many appointments did each specialization handle?
select specialization,count(appointment_id) as Total_count
from appointment_sheet
right join doctors_sheet
on appointment_sheet.doctor_id=doctors_sheet.doctor_id
group by specialization
order by Total_Count desc;


#17.Which treatment type was performed the most?
select treatment_type,count(treatment_id) as total_Count
from treatment_sheet
group by treatment_type
order by total_count desc;


#18.How many patients visited multiple Times.
select `Full Name`,count(patient_id) as total_Visit
from patient_sheet
group by `Full Name`
order by total_visit desc
limit 10;


#19.Which branch has the highest number of patients?
select hospital_Branch,count(patient_id) as Total_Patients
from appointment_sheet
left join doctors_sheet
on appointment_sheet.doctor_id=doctors_sheet.doctor_id
group by hospital_branch
order by Total_Patients desc; 


#20.What is the revenue generated by each payment method?
select payment_method,sum(amount) revenue_generated
from billing_sheet 
group by payment_method
order by revenue_generated desc;


#21.Who are the top 5 patients by total spending?
select `full Name`,sum(amount) as Total_Amount
from patient_sheet
left join billing_sheet
on patient_sheet.patient_id=billing_sheet.patient_id
group by `full Name`
order by Total_Amount desc
limit 5;


#22.What is the average revenue per patient?
select `Full Name`,avg(amount) as avg_amount
from patient_sheet
join billing_sheet
on patient_sheet.patient_id=billing_sheet.patient_id
group by `Full Name`
order by avg_amount;


#23.Which month had the highest revenue?
SELECT 
MONTH(STR_TO_DATE(appointment_date, '%Y-%m-%d')) AS month,
sum(amount) AS total_Revenue
FROM appointment_sheet
join billing_sheet
on appointment_sheet.patient_id=billing_sheet.patient_id
GROUP BY month
ORDER BY month desc
limit 1;


#24.Which treatment type generated the most revenue?
select treatment_type,sum(cost) as Total_Revenue
from treatment_sheet
group by treatment_type
order by total_revenue desc
limit 1;


#25.Find patients who spent above the overall average patient spending.
select `Full Name`,amount as avg_amount
from patient_sheet
join billing_sheet
on patient_sheet.patient_id=billing_sheet.patient_id
where amount>(select avg(amount) from billing_sheet);

































